### ISSUE TITLE
Request: command to toggle UI

### ISSUE THREAD

**Issue by VariableVixen** [AtmoOmen/CurrencyTracker#1]
Right now, if I want to see my stats, I need to open the plugin installer, find CurrencyTracker in the list, and use the settings button. It would be much more convenient if there was a command that I could use, particularly for making a macro or QoLBar button.

This command could possibly also take a (partial?) current name to open the display to the given currency for additional convenience.

**Comment by AtmoOmen** [comment]
In the latest update, I have added a command to open the main window of the plugin.

Regarding the latter point you mentioned, due to the current plugin's logic being developed based on multi-language support, and also because the code logic for custom currency and preset currency differs slightly, I will first attempt to merge the code logic for custom currency and plugin preset currency in subsequent versions. After that, I will attempt to develop the feature you mentioned.
