### ISSUE TITLE
Bug: filtering and sorting options don't update the displayed table correctly

### ISSUE THREAD

**Issue by VariableVixen** [AtmoOmen/CurrencyTracker#2]
- Changing the filtering options in a way that _removes_ entries from the list updates live, but changing then in a way that should _add_ entries to the list (such as by decreasing the "cluster by time" option to ungroup items) does not update the list.
- Changing "filter by change" from "above" to "below" or vice versa empties the list until you navigate to a different currency tab and then back.
- Toggling the "reverse sorting" option doesn't update the table until you navigate to a different currency tab and then back; even changing filtering options doesn't change the sort order.

It looks like changing the filtering options causes the list to be filtered not from the raw data but from the entries currently displayed in the list, and the "reverse sorting" option apparently only applies when the list is _initially_ built. Changing any of the sorting and filtering options should probably rebuild the displayed list from the raw data in order to function as expected.

**Comment by AtmoOmen** [comment]
Thank you for your report. The issue has now been identified in the code.
This problem arose because in the latest version update, I attempted to cache the transaction records on the first page to alleviate the lag caused by a large amount of data. However, I did not conduct further testing on the functionality related to filters. The issue has been fixed now, and I will push an update later to address this.
I'm also sorry for any inconvenience this may have caused.

**Comment by VariableVixen** [comment]
All good! I figured it was because of the optimisations for large records mentioned in recent commits, but I wanted to report it in the hopes that some kind of middle ground could be reached. Glad to hear you found a way, and thanks for the cool plugin!

**Comment by VariableVixen** [comment]
This looks to be fixed, according to me poking around with the options in my game.
