### ISSUE TITLE
Tracking Improvement

### ISSUE THREAD

**Issue by ArcaneInferno** [AtmoOmen/CurrencyTracker#20]
Hi,

Can I make a suggestion on to improve the tracking of items/currency.

At the moment the plugin tracks literally everything that passes through trade, retainer and whether its an item, currency and crystals.

Could you only make it so it only tracks what's been selected to track on the left column of the list of things to track?

I notice in the character folder it is generating a lot of file that I'm not tracking and it still output the tracking data for it and this leads me to my next point.

I've notice a massive performance issue with the plugin after I've traded several stacks of item that's in 999 and I'm struggling to reproduce the issue because I'm trying to track down what is the cause of it. But, I believe it is something to do with tracking many stacks of items that's 999 possibly causes the plugin to fire off and go through each individual items and then log the information out.

Over time it comes to a point when you confirm trade, it will just freeze the game for like 3-5 seconds depends how quickly it unfreeze before the server thinks you've disconnected and throw you back to the login screen

Also, today when I was trading gil to a friend and they've giving me item. There's seems to be a glitch where there's ghost entries on the gil tracking table but if i were to delete 1 entry everything just disappears.

So, I'm not too sure if trading multiple stacks of items along with the gil cause multiple entries being inserted into the table.

The only remedy it'd fix the freeze once it started is to unload the plugin and reload it or restart the game entirely.

Many Thanks.

**Comment by AtmoOmen** [comment]
I've pushed an update to fix the issue where the Trade module has a higher performance consumption than expected, you can update asap to see if the same issue happen again. I've been working hard to reduce the overall performance consumption of the plugin, both in terms of background running logic as well as interface drawing logic.

About the tracking mode, the old tracking logic is that it will only generate the data files from currencies/items you've selected, but due to the two main reasons, I changed that into the current logic:
1. I plan to add a feature to let users see what they exchange for with their currencies/items in the form of a list in the note part of one transaction. And also because the storage logic (the plugin does not storage current amount of items like Allagan Tools does but only storage the history transactions), so it's a must to storage other currencies/items' data files.
2. Main tracking logic is composed by modules, and each module implements their own function separately, so it's hard and unreasonable to have two different tracking logics coexist at a lower level, and to have all modules design two completely different execution processes for the two logics

But I will try to add more indicators to indicate which data file belong to which currency, and there will also be a popup or window in the later update to show correspondence between data files and specific currencies like your retainer, (premium) saddle bag or maybe FC chest later.

All in all, thanks for suggestions and reports~
Also, if you have any better ideas for code/logic improvement, feel free to comment/open a new issue/pull request!
